repos:
-   repo: local
    hooks:
    -   id: ruff-check
        name: ruff-check
        entry: ruff check --fix
        types_or: [ python, pyi ]
        language: python
        require_serial: true
    -   id: ruff-format
        name: ruff-format
        entry: ruff format
        language: python
        types_or: [ python, pyi ]
        require_serial: true
