name: Testing

on: [push]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file env.yaml --name base
    - name: Test with pytest
      run: |
        python -m pytest hps/test/
  # accuracy-tests:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     max-parallel: 5

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up Python 3.10
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: 3.10.8
  #   - name: Add conda to system path
  #     run: |
  #       # $CONDA is an environment variable pointing to the root of the miniconda directory
  #       echo $CONDA/bin >> $GITHUB_PATH
  #   - name: Install dependencies
  #     run: |
  #       conda env update --file env.yaml --name base
  #   - name: Run accuracy checks
  #     run: |
  #       python run_all_checks.py -a
